/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-01-07 07:22:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.db.connection.DAOConnection;
import java.sql.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1704535111546L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1704611889426L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.db.connection.DAOConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("	");
 String email=session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("	   <h3>Online Shopping</h3>\r\n");
      out.write("	   \r\n");
      out.write("		<ul>\r\n");
      out.write("		   <li><a href=\"\">");
 out.println(email);
      out.write("<i class=\"fa fa-user\"></i></a></li>\r\n");
      out.write("			<li><a href=\"home.jsp\">Home<i class=\"fa fa-institution\"></i></a></li>\r\n");
      out.write("			<li><a href=\"\">My Cart<i class=\"fa fa-cart-arrow-down\"></i></a></li>\r\n");
      out.write("			<li><a href=\"\">My Orders<i class=\"fa fa-check-square\"></i></a></li>\r\n");
      out.write("			<li><a href=\"\">Change Details<i class=\"fa fa-edit\"></i></a></li>\r\n");
      out.write("			<li><a href=\"\">Message Us<i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("			<li><a href=\"\">About<i class=\"fa fa-address-book\"></i></a></li>\r\n");
      out.write("			<li><a href=\"logout.jsp\">Logout<i class=\"fa fa-sign-out\"></i></a></li>\r\n");
      out.write("			 <div class=\"search-container\">\r\n");
      out.write("			 <form action=\"search-home.jsp\" method=\"post\">\r\n");
      out.write("        	<input type=\"text\" placeholder=\"Search..\" name=\"search\">\r\n");
      out.write("            <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("        	</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("       \r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/home-style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"product-view\">\r\n");
      out.write("<h3 style=\"color: white; text-align: center;\">Home &nbsp;<i class=\"fa fa-institution\"></i></h3>\r\n");

String msg=request.getParameter("msg");
if(msg!=null &&  msg.equals("added")){

      out.write("\r\n");
      out.write("<h3 class=\"success-msg\">Product Added Successfully...</h3>\r\n");

}

      out.write('\r');
      out.write('\n');
if(msg!=null && msg.equals("exist")){

      out.write("\r\n");
      out.write("<h3 class=\"failure-msg\">Product already exist in your cart!Quantity Increased!</h3>\r\n");
} 
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>ID</th>\r\n");
      out.write("			<th>NAME</th>\r\n");
      out.write("			<th>CATEGORY</th>\r\n");
      out.write("			<th><i class=\"fa fa-inr\"></i>PRICE</th>\r\n");
      out.write("			<th>ADD TO CART<i class=\"fa fa-cart-arrow-down\"></i></th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

	try {
		Connection con = DAOConnection.getConnection();
		Statement stmt = con.createStatement();
		ResultSet rs = stmt.executeQuery("select * from product where active='yes'");
		while(rs.next())
		{
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>");
      out.print( rs.getString(1));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(2));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(3));
      out.write("</td>\r\n");
      out.write("			<td><i class=\"fa fa-inr\"></i>");
      out.print( rs.getString(4));
      out.write("</td>\r\n");
      out.write("			<td><a href=\"addToCartAction.jsp?id=");
      out.print( rs.getString(1));
      out.write("\">Add to cart<i class=\"fa fa-cart-arrow-down\"></i></a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
}
	} catch (Exception e) {
      e.printStackTrace();
	}
	
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("<p>All rights recieved</p>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
